import { Either, getOk, isErr, ok, Result } from "elfs";
import { Error, Pipeable, PipeableAsync } from "../types";

export function and<$Input, $Output_1, $Error_1 extends Error>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
): PipeableAsync<$Input, Result<$Output_1, Either<[$Error_1]>>>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
): PipeableAsync<$Input, Result<$Output_2, Either<[$Error_1, $Error_2]>>>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
): PipeableAsync<
  $Input,
  Result<$Output_3, Either<[$Error_1, $Error_2, $Error_3]>>
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
): PipeableAsync<
  $Input,
  Result<$Output_4, Either<[$Error_1, $Error_2, $Error_3, $Error_4]>>
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
): PipeableAsync<
  $Input,
  Result<$Output_5, Either<[$Error_1, $Error_2, $Error_3, $Error_4, $Error_5]>>
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_6,
    Either<[$Error_1, $Error_2, $Error_3, $Error_4, $Error_5, $Error_6]>
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_7,
    Either<
      [$Error_1, $Error_2, $Error_3, $Error_4, $Error_5, $Error_6, $Error_7]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_8,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_9,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_10,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_11,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_12,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_13,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_14,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_15,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_16,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_17,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_18,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_19,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_20,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_21,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_22,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_23,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_24,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_25,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_26,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
  $Output_27,
  $Error_27 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
  pipeable_26_27: Pipeable<$Output_26, Result<$Output_27, $Error_27>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_27,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
        $Error_27,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
  $Output_27,
  $Error_27 extends Error,
  $Output_28,
  $Error_28 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
  pipeable_26_27: Pipeable<$Output_26, Result<$Output_27, $Error_27>>,
  pipeable_27_28: Pipeable<$Output_27, Result<$Output_28, $Error_28>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_28,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
        $Error_27,
        $Error_28,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
  $Output_27,
  $Error_27 extends Error,
  $Output_28,
  $Error_28 extends Error,
  $Output_29,
  $Error_29 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
  pipeable_26_27: Pipeable<$Output_26, Result<$Output_27, $Error_27>>,
  pipeable_27_28: Pipeable<$Output_27, Result<$Output_28, $Error_28>>,
  pipeable_28_29: Pipeable<$Output_28, Result<$Output_29, $Error_29>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_29,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
        $Error_27,
        $Error_28,
        $Error_29,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
  $Output_27,
  $Error_27 extends Error,
  $Output_28,
  $Error_28 extends Error,
  $Output_29,
  $Error_29 extends Error,
  $Output_30,
  $Error_30 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
  pipeable_26_27: Pipeable<$Output_26, Result<$Output_27, $Error_27>>,
  pipeable_27_28: Pipeable<$Output_27, Result<$Output_28, $Error_28>>,
  pipeable_28_29: Pipeable<$Output_28, Result<$Output_29, $Error_29>>,
  pipeable_29_30: Pipeable<$Output_29, Result<$Output_30, $Error_30>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_30,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
        $Error_27,
        $Error_28,
        $Error_29,
        $Error_30,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
  $Output_27,
  $Error_27 extends Error,
  $Output_28,
  $Error_28 extends Error,
  $Output_29,
  $Error_29 extends Error,
  $Output_30,
  $Error_30 extends Error,
  $Output_31,
  $Error_31 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
  pipeable_26_27: Pipeable<$Output_26, Result<$Output_27, $Error_27>>,
  pipeable_27_28: Pipeable<$Output_27, Result<$Output_28, $Error_28>>,
  pipeable_28_29: Pipeable<$Output_28, Result<$Output_29, $Error_29>>,
  pipeable_29_30: Pipeable<$Output_29, Result<$Output_30, $Error_30>>,
  pipeable_30_31: Pipeable<$Output_30, Result<$Output_31, $Error_31>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_31,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
        $Error_27,
        $Error_28,
        $Error_29,
        $Error_30,
        $Error_31,
      ]
    >
  >
>;
export function and<
  $Input,
  $Output_1,
  $Error_1 extends Error,
  $Output_2,
  $Error_2 extends Error,
  $Output_3,
  $Error_3 extends Error,
  $Output_4,
  $Error_4 extends Error,
  $Output_5,
  $Error_5 extends Error,
  $Output_6,
  $Error_6 extends Error,
  $Output_7,
  $Error_7 extends Error,
  $Output_8,
  $Error_8 extends Error,
  $Output_9,
  $Error_9 extends Error,
  $Output_10,
  $Error_10 extends Error,
  $Output_11,
  $Error_11 extends Error,
  $Output_12,
  $Error_12 extends Error,
  $Output_13,
  $Error_13 extends Error,
  $Output_14,
  $Error_14 extends Error,
  $Output_15,
  $Error_15 extends Error,
  $Output_16,
  $Error_16 extends Error,
  $Output_17,
  $Error_17 extends Error,
  $Output_18,
  $Error_18 extends Error,
  $Output_19,
  $Error_19 extends Error,
  $Output_20,
  $Error_20 extends Error,
  $Output_21,
  $Error_21 extends Error,
  $Output_22,
  $Error_22 extends Error,
  $Output_23,
  $Error_23 extends Error,
  $Output_24,
  $Error_24 extends Error,
  $Output_25,
  $Error_25 extends Error,
  $Output_26,
  $Error_26 extends Error,
  $Output_27,
  $Error_27 extends Error,
  $Output_28,
  $Error_28 extends Error,
  $Output_29,
  $Error_29 extends Error,
  $Output_30,
  $Error_30 extends Error,
  $Output_31,
  $Error_31 extends Error,
  $Output_32,
  $Error_32 extends Error,
>(
  pipeable_0_1: Pipeable<$Input, Result<$Output_1, $Error_1>>,
  pipeable_1_2: Pipeable<$Output_1, Result<$Output_2, $Error_2>>,
  pipeable_2_3: Pipeable<$Output_2, Result<$Output_3, $Error_3>>,
  pipeable_3_4: Pipeable<$Output_3, Result<$Output_4, $Error_4>>,
  pipeable_4_5: Pipeable<$Output_4, Result<$Output_5, $Error_5>>,
  pipeable_5_6: Pipeable<$Output_5, Result<$Output_6, $Error_6>>,
  pipeable_6_7: Pipeable<$Output_6, Result<$Output_7, $Error_7>>,
  pipeable_7_8: Pipeable<$Output_7, Result<$Output_8, $Error_8>>,
  pipeable_8_9: Pipeable<$Output_8, Result<$Output_9, $Error_9>>,
  pipeable_9_10: Pipeable<$Output_9, Result<$Output_10, $Error_10>>,
  pipeable_10_11: Pipeable<$Output_10, Result<$Output_11, $Error_11>>,
  pipeable_11_12: Pipeable<$Output_11, Result<$Output_12, $Error_12>>,
  pipeable_12_13: Pipeable<$Output_12, Result<$Output_13, $Error_13>>,
  pipeable_13_14: Pipeable<$Output_13, Result<$Output_14, $Error_14>>,
  pipeable_14_15: Pipeable<$Output_14, Result<$Output_15, $Error_15>>,
  pipeable_15_16: Pipeable<$Output_15, Result<$Output_16, $Error_16>>,
  pipeable_16_17: Pipeable<$Output_16, Result<$Output_17, $Error_17>>,
  pipeable_17_18: Pipeable<$Output_17, Result<$Output_18, $Error_18>>,
  pipeable_18_19: Pipeable<$Output_18, Result<$Output_19, $Error_19>>,
  pipeable_19_20: Pipeable<$Output_19, Result<$Output_20, $Error_20>>,
  pipeable_20_21: Pipeable<$Output_20, Result<$Output_21, $Error_21>>,
  pipeable_21_22: Pipeable<$Output_21, Result<$Output_22, $Error_22>>,
  pipeable_22_23: Pipeable<$Output_22, Result<$Output_23, $Error_23>>,
  pipeable_23_24: Pipeable<$Output_23, Result<$Output_24, $Error_24>>,
  pipeable_24_25: Pipeable<$Output_24, Result<$Output_25, $Error_25>>,
  pipeable_25_26: Pipeable<$Output_25, Result<$Output_26, $Error_26>>,
  pipeable_26_27: Pipeable<$Output_26, Result<$Output_27, $Error_27>>,
  pipeable_27_28: Pipeable<$Output_27, Result<$Output_28, $Error_28>>,
  pipeable_28_29: Pipeable<$Output_28, Result<$Output_29, $Error_29>>,
  pipeable_29_30: Pipeable<$Output_29, Result<$Output_30, $Error_30>>,
  pipeable_30_31: Pipeable<$Output_30, Result<$Output_31, $Error_31>>,
  pipeable_31_32: Pipeable<$Output_31, Result<$Output_32, $Error_32>>,
): PipeableAsync<
  $Input,
  Result<
    $Output_32,
    Either<
      [
        $Error_1,
        $Error_2,
        $Error_3,
        $Error_4,
        $Error_5,
        $Error_6,
        $Error_7,
        $Error_8,
        $Error_9,
        $Error_10,
        $Error_11,
        $Error_12,
        $Error_13,
        $Error_14,
        $Error_15,
        $Error_16,
        $Error_17,
        $Error_18,
        $Error_19,
        $Error_20,
        $Error_21,
        $Error_22,
        $Error_23,
        $Error_24,
        $Error_25,
        $Error_26,
        $Error_27,
        $Error_28,
        $Error_29,
        $Error_30,
        $Error_31,
        $Error_32,
      ]
    >
  >
>;
/**
 * Async pipeable which takes N number of sync or async pipeables and returns either `Ok` returned by the last pipeable or `Err` returned by any of the pipeables.
 *
 * @example
 * // PipeableAsync<number, Result<string, Error<"FILTER", number> | Error<"CUSTOM", number>>>
 * const customPipe = pipe(
 *   filter((v: number) => !(v % 2)),
 *   wrap(
 *     map((v) => `${v}`),
 *     error("CUSTOM")
 *   ),
 * );
 **/
export function and(...pipeables: Pipeable[]) {
  const length = pipeables.length;

  return async (value: unknown) => {
    let latest = value;

    for (let i = 0; i < length; ++i) {
      const result = await pipeables[i](latest);

      if (isErr(result)) {
        return result;
      }

      latest = getOk(result);
    }

    return ok(latest);
  };
}

export const andAsync = and;
